### ISSUE TITLE
Name Redefinition Problem of variable and function

### ISSUE THREAD

**Issue by iamNCJ** [PAN-Ziyue/GNC#16]
```c
int main() {
    return 0;
}

int main = 0;
```

Expected Behavior: 
> test.c:9:5: error: redefinition of 'main' as different kind of symbol
> int main = 0;
>     ^
> test.c:3:5: note: previous definition is here
> int main()
>     ^
> test.c:9:1: warning: variable named 'main' with external linkage has undefined behavior [-Wmain]
> int main = 0;
> ^
> 1 warning and 1 error generated.

Current Behavior:

![image](https://user-images.githubusercontent.com/28685287/120578430-61afa800-c458-11eb-9876-a613c4e1d144.png)

**Comment by PAN-Ziyue** [comment]
![image](https://user-images.githubusercontent.com/50222787/120580611-10091c80-c45c-11eb-8ddd-fe0360520e6c.png)

Fixed.
