### ISSUE TITLE
Functions begin with _

### ISSUE THREAD

**Issue by iamNCJ** [PAN-Ziyue/GNC#17]
```c
#include <stdio.h>

void _main(){}

int main()
{
    printf("Hello world\n");
    return 0;
}
```

![image](https://user-images.githubusercontent.com/28685287/120788267-dff87100-c562-11eb-95e2-3199f4d52870.png)

**Comment by PAN-Ziyue** [comment]
Fixed. Tiny bug in the grammar script

![image](https://user-images.githubusercontent.com/50222787/120825174-b1db5700-c58b-11eb-84d7-d3837465e687.png)
